[package]
name = "advent_21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitreader = "0.3.5"
hex = "0.4.3"
lazy_static = "1.4.0"
regex = "1"
